local mason = {
  {
    "mason-org/mason.nvim",
    lazy = true,
    opts = {
      ensure_installed = {
        "clangd",
        "pyright",
        "rubocop",
        "lua-language-server",
        "html-lsp",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "tailwindcss-language-server",
        "solang",
        "typescript-language-server",
        "solhint",
        "solargraph",
        "ruby-lsp",
        "sqlls",
        "python-lsp-server",
        "gopls",
        "prisma-language-server",
        "rust-analyzer",
        "vue-language-server",
        "astro",
        "jdtls",
        ----FORMATERS-----
        "stylua",
        "rubyfmt",
        "htmlbeautifier",
        "beautysh",
        "yamlfix",
        "prettierd",
        "gofumpt",
        "goimports_reviser",
        "xmllint",
        "biome",
        "ruff",
        "google-java-format",
        ----DEBUGGERS----,
        "debugpy",
      },
    },
  },
}
return mason
